// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: notify.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

///请求参数
///notify/add
struct Protogo_AddNotifyRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 预约时间
  var appointTime: String = String()

  /// 客户姓名
  var customerName: String = String()

  /// 客户手机
  var customerPhone: String = String()

  /// 客户imaccid
  var customerAccid: String = String()

  /// 员工imaccid
  var employeeAccid: String = String()

  /// 医院名字
  var hospitalName: String = String()

  /// 项目名
  var serviceName: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Protogo_AddNotifyResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var status: Protogo_BaseResponse {
    get {return _status ?? Protogo_BaseResponse()}
    set {_status = newValue}
  }
  /// Returns true if `status` has been explicitly set.
  var hasStatus: Bool {return self._status != nil}
  /// Clears the value of `status`. Subsequent reads from it will return its default value.
  mutating func clearStatus() {self._status = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _status: Protogo_BaseResponse? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "protogo"

extension Protogo_AddNotifyRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AddNotifyRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "appoint_time"),
    2: .standard(proto: "customer_name"),
    3: .standard(proto: "customer_phone"),
    4: .standard(proto: "customer_accid"),
    5: .standard(proto: "employee_accid"),
    6: .standard(proto: "hospital_name"),
    7: .standard(proto: "service_name"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.appointTime)
      case 2: try decoder.decodeSingularStringField(value: &self.customerName)
      case 3: try decoder.decodeSingularStringField(value: &self.customerPhone)
      case 4: try decoder.decodeSingularStringField(value: &self.customerAccid)
      case 5: try decoder.decodeSingularStringField(value: &self.employeeAccid)
      case 6: try decoder.decodeSingularStringField(value: &self.hospitalName)
      case 7: try decoder.decodeSingularStringField(value: &self.serviceName)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.appointTime.isEmpty {
      try visitor.visitSingularStringField(value: self.appointTime, fieldNumber: 1)
    }
    if !self.customerName.isEmpty {
      try visitor.visitSingularStringField(value: self.customerName, fieldNumber: 2)
    }
    if !self.customerPhone.isEmpty {
      try visitor.visitSingularStringField(value: self.customerPhone, fieldNumber: 3)
    }
    if !self.customerAccid.isEmpty {
      try visitor.visitSingularStringField(value: self.customerAccid, fieldNumber: 4)
    }
    if !self.employeeAccid.isEmpty {
      try visitor.visitSingularStringField(value: self.employeeAccid, fieldNumber: 5)
    }
    if !self.hospitalName.isEmpty {
      try visitor.visitSingularStringField(value: self.hospitalName, fieldNumber: 6)
    }
    if !self.serviceName.isEmpty {
      try visitor.visitSingularStringField(value: self.serviceName, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Protogo_AddNotifyRequest, rhs: Protogo_AddNotifyRequest) -> Bool {
    if lhs.appointTime != rhs.appointTime {return false}
    if lhs.customerName != rhs.customerName {return false}
    if lhs.customerPhone != rhs.customerPhone {return false}
    if lhs.customerAccid != rhs.customerAccid {return false}
    if lhs.employeeAccid != rhs.employeeAccid {return false}
    if lhs.hospitalName != rhs.hospitalName {return false}
    if lhs.serviceName != rhs.serviceName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Protogo_AddNotifyResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AddNotifyResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "status"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._status)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._status {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Protogo_AddNotifyResponse, rhs: Protogo_AddNotifyResponse) -> Bool {
    if lhs._status != rhs._status {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
